# Generated by Django 5.2.11 on 2026-02-20 21:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ig_id", models.CharField(max_length=32, unique=True)),
                (
                    "ig_media_type",
                    models.CharField(
                        choices=[
                            ("CAROUSEL_ALBUM", "CAROUSEL_ALBUM"),
                            ("IMAGE", "IMAGE"),
                            ("VIDEO", "VIDEO"),
                        ],
                        max_length=14,
                    ),
                ),
                (
                    "ig_media_url",
                    models.TextField(
                        validators=[django.core.validators.URLValidator()]
                    ),
                ),
                ("ig_timestamp", models.DateTimeField()),
                ("ig_caption", models.CharField(blank=True, max_length=2200)),
                ("ig_comments_count", models.PositiveIntegerField()),
                ("ig_like_count", models.PositiveIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ig_id", models.CharField(max_length=32, unique=True)),
                ("ig_text", models.TextField()),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="posts.post",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ChildrenMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ig_id", models.CharField(max_length=32, unique=True)),
                (
                    "ig_media_type",
                    models.CharField(
                        choices=[
                            ("CAROUSEL_ALBUM", "CAROUSEL_ALBUM"),
                            ("IMAGE", "IMAGE"),
                            ("VIDEO", "VIDEO"),
                        ],
                        max_length=14,
                    ),
                ),
                (
                    "ig_media_url",
                    models.TextField(
                        validators=[django.core.validators.URLValidator()]
                    ),
                ),
                ("ig_timestamp", models.DateTimeField()),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children_medias",
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
